/* 입양 시각 구하기 */
SELECT HOUR(DATETIME) AS 'HOUR', COUNT(*)
FROM ANIMAL_OUTS
GROUP BY HOUR
HAVING HOUR >= 9 AND HOUR <= 19
ORDER BY HOUR;

/* 입양 시각 구하기 (2) */
/* @변수명 */
SET @HOUR_LIST = -1;

SELECT
(@HOUR_LIST := @HOUR_LIST + 1) AS 'HOUR',
(SELECT COUNT(*) FROM ANIMAL_OUTS WHERE @HOUR_LIST = HOUR(DATETIME)) AS 'COUNT'
FROM ANIMAL_OUTS
WHERE @HOUR_LIST < 23;